url: https://bandacomunalerezzato.it
#baseurl: /BandaComunaleRezzato
title: Associazione Banda Comunale di Rezzato
description: ""
locale: 'it'
repository: oniram88/BandaComunaleRezzato

paginate: 15
logo: "/assets/images/logo.png"
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll

#minimal_mistakes_skin: "air" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-gallery-generator

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .github
  - custom_helpers
  - wp-content
include:
  - "_pages"
  - "assets"

collections:
  insegnanti:
    output: true
    permalink: /accademia-musicale/:collection/:path/
  concerti:
    output: true
    permalink: /banda/concerti/:collection/:path/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # pagine della banda
  - scope:
      path: "_pages/banda"
      type: pages
    values:
      sidebar:
        nav: "side_banda"
  # pagine dell'accademia
  - scope:
      path: "_pages/accademia-musicale"
      type: pages
    values:
      sidebar:
        nav: "side_accademia"
  # pagine per gli insegnanti
  - scope:
      path: ""
      type: insegnanti
    values:
      layout: single
      sidebar:
        nav: "side_accademia"
  # pagine per gli concerti
  - scope:
      path: ""
      type: concerti
    values:
      layout: single
      sidebar:
        nav: "side_banda"
  - scope:
      path: "_pages/informazioni"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "side_contatti"
  - scope:
      path: ""
      type: posts
    values:
      layout: single

footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/bandacomunalerezzato"


gallery:
  dir: galleries               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: ""  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
  # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    bottega-alta-settembre-2015:
      best_image: 12030279_512120862297711_7536374472970817580_o.jpg
    hartmann:
      best_image: hartman-8.jpg
#    concerti:
#      best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
#    japan_trip:
#      best_image: IMG_0690.JPG
#      name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
#    awesome_stuff:
#      best_image: snaileo_gonzales.jpg
#      sort_reverse: true    # Reverse sort images in gallery.
#    secret_stuff:
#      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
#    with_info:
#      info: