url: http://www.bandacomunalerezzato.it
title: Associazione Banda Comunale di Rezzato
description: ""
locale: 'it'
repository: oniram88/BandaComunaleRezzato

teaser: '/assets/images/header_default.jpg'
logo: "/assets/images/logo.png"
# Build settings
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
include:
  - "_pages"
  - "assets"


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: "_pages/banda"
      type: pages
    values:
      sidebar:
        nav: "side_banda"